# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
