# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password2',
            field=models.CharField(max_length=20),
            preserve_default=True,
        ),
    ]
