# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_userprofile_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password2',
            new_name='re_password',
        ),
    ]
