# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160303_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='re_password',
        ),
    ]
