# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_userprofile_re_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbit',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='fitbit',
            name='updated',
        ),
    ]
