# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160312_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
