# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20160312_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fitbit',
        ),
    ]
