# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_anklet_noise_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerometer',
            fields=[
                ('idaccelerometer', models.IntegerField(db_column='idAccelerometer', primary_key=True, serialize=False)),
                ('orientation', models.IntegerField(blank=True, null=True)),
                ('xcoord', models.IntegerField(blank=True, db_column='xCoord', null=True)),
                ('ycoord', models.IntegerField(blank=True, db_column='yCoord', null=True)),
                ('zcoord', models.IntegerField(blank=True, db_column='zCoord', null=True)),
                ('timemeasured', models.DateTimeField(blank=True, db_column='timeMeasured', null=True)),
            ],
            options={
                'db_table': 'accelerometer',
            },
        ),
        migrations.CreateModel(
            name='Activitylevel',
            fields=[
                ('idactivitylevel', models.IntegerField(db_column='idactivityLevel', primary_key=True, serialize=False)),
                ('standingpercentage', models.IntegerField(blank=True, db_column='standingPercentage', null=True)),
                ('walkingpercentage', models.IntegerField(blank=True, db_column='walkingPercentage', null=True)),
                ('runningpercentage', models.IntegerField(blank=True, db_column='runningPercentage', null=True)),
                ('lyingdownpercentage', models.IntegerField(blank=True, db_column='lyingDownPercentage', null=True)),
                ('sleepingpercentage', models.IntegerField(blank=True, db_column='sleepingPercentage', null=True)),
            ],
            options={
                'db_table': 'activityLevel',
            },
        ),
        migrations.CreateModel(
            name='AnkletGeneral',
            fields=[
                ('idanklet', models.IntegerField(db_column='idAnklet', primary_key=True, serialize=False)),
                ('ankletnum', models.IntegerField(blank=True, db_column='ankletNum', null=True, unique=True)),
                ('lastdatareceivedtime', models.DateTimeField(blank=True, db_column='lastDataReceivedTime', null=True)),
                ('createddate', models.DateField(blank=True, db_column='createdDate', null=True)),
            ],
            options={
                'db_table': 'anklet_general',
            },
        ),
        migrations.CreateModel(
            name='Cowculatedlocation',
            fields=[
                ('idcowculatedlocation', models.IntegerField(db_column='idCowculatedLocation', primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('xcoord', models.FloatField(blank=True, db_column='xCoord', null=True)),
                ('ycoord', models.FloatField(blank=True, db_column='yCoord', null=True)),
                ('timecalculated', models.DateTimeField(blank=True, db_column='timeCalculated', null=True)),
                ('idanklet', models.ForeignKey(blank=True, db_column='idAnklet', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AnkletGeneral')),
            ],
            options={
                'db_table': 'cowculatedLocation',
            },
        ),
        migrations.CreateModel(
            name='CowGeneral',
            fields=[
                ('idcow', models.IntegerField(db_column='idCow', primary_key=True, serialize=False)),
                ('cownum', models.IntegerField(db_column='cowNum', unique=True)),
                ('cowname', models.CharField(blank=True, db_column='cowName', max_length=45, null=True)),
                ('cowbirthdate', models.DateField(blank=True, db_column='cowBirthDate', null=True)),
                ('cowdeathdate', models.DateField(blank=True, db_column='cowDeathDate', null=True)),
            ],
            options={
                'db_table': 'cow_general',
            },
        ),
        migrations.CreateModel(
            name='Cowgroups',
            fields=[
                ('idcowgroups', models.IntegerField(db_column='idCowGroups', primary_key=True, serialize=False)),
                ('lastupdated', models.DateTimeField(blank=True, db_column='lastUpdated', null=True)),
                ('idcow', models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral')),
            ],
            options={
                'db_table': 'cowGroups',
            },
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('idfriendships', models.IntegerField(db_column='idFriendships', primary_key=True, serialize=False)),
                ('friendlevel', models.IntegerField(db_column='friendLevel')),
                ('friendshipscore', models.IntegerField(db_column='friendshipScore')),
                ('lastupdated', models.DateTimeField(blank=True, db_column='lastUpdated', null=True)),
                ('idcowfriend', models.ForeignKey(blank=True, db_column='idCowFriend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cowfriend', to='website.CowGeneral')),
                ('idcoworiginal', models.ForeignKey(blank=True, db_column='idCowOriginal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coworiginal', to='website.CowGeneral')),
            ],
            options={
                'db_table': 'friendships',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('idlocation', models.IntegerField(db_column='idLocation', primary_key=True, serialize=False)),
                ('rssivalue', models.IntegerField(blank=True, db_column='rssiValue', null=True)),
                ('timemeasured', models.DateTimeField(blank=True, db_column='timeMeasured', null=True)),
                ('idanklet', models.ForeignKey(blank=True, db_column='idAnklet', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AnkletGeneral')),
                ('idcow', models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('idmicrophone', models.IntegerField(db_column='idMicrophone', primary_key=True, serialize=False)),
                ('noiselevel', models.IntegerField(blank=True, db_column='noiseLevel', null=True)),
                ('timemeasured', models.DateTimeField(blank=True, db_column='timeMeasured', null=True)),
                ('idanklet', models.ForeignKey(blank=True, db_column='idAnklet', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AnkletGeneral')),
                ('idcow', models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral')),
            ],
            options={
                'db_table': 'microphone',
            },
        ),
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('idpulse', models.IntegerField(db_column='idPulse', primary_key=True, serialize=False)),
                ('pulselevel', models.IntegerField(blank=True, db_column='pulseLevel', null=True)),
                ('timemeasured', models.DateTimeField(blank=True, db_column='timeMeasured', null=True)),
                ('idanklet', models.ForeignKey(blank=True, db_column='idAnklet', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AnkletGeneral')),
                ('idcow', models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral')),
            ],
            options={
                'db_table': 'pulse',
            },
        ),
        migrations.CreateModel(
            name='Sociallevel',
            fields=[
                ('idsociallevel', models.IntegerField(db_column='idSocialLevel', primary_key=True, serialize=False)),
                ('sociallevel', models.IntegerField(blank=True, db_column='socialLevel', null=True)),
                ('timecalculated', models.DateTimeField(blank=True, db_column='timeCalculated', null=True)),
                ('idcow', models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral')),
            ],
            options={
                'db_table': 'socialLevel',
            },
        ),
        migrations.CreateModel(
            name='Staticnode',
            fields=[
                ('idstaticnode', models.IntegerField(db_column='idStaticNode', primary_key=True, serialize=False)),
                ('staticnodenum', models.IntegerField(blank=True, db_column='staticNodeNum', null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('xcoord', models.FloatField(blank=True, db_column='xCoord', null=True)),
                ('ycoord', models.FloatField(blank=True, db_column='yCoord', null=True)),
                ('staticnodecol', models.CharField(blank=True, db_column='staticNodecol', max_length=45, null=True)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staticNode',
            },
        ),
        migrations.CreateModel(
            name='Stepcount',
            fields=[
                ('idstepcount', models.IntegerField(db_column='idstepCount', primary_key=True, serialize=False)),
                ('datastarttime', models.DateTimeField(blank=True, db_column='dataStartTime', null=True)),
                ('dataendtime', models.DateTimeField(blank=True, db_column='dataEndTime', null=True)),
                ('stepcount', models.IntegerField(blank=True, db_column='stepCount', null=True)),
                ('idcow', models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral')),
            ],
            options={
                'db_table': 'stepCount',
            },
        ),
        migrations.RemoveField(
            model_name='anklet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='noise',
            name='anklet',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='anklet',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='id',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='temperature',
            name='idtemperature',
            field=models.IntegerField(db_column='idTemperature', default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperaturelevel',
            field=models.IntegerField(blank=True, db_column='temperatureLevel', null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='timemeasured',
            field=models.DateTimeField(blank=True, db_column='timeMeasured', null=True),
        ),
        migrations.AlterModelTable(
            name='temperature',
            table='temperature',
        ),
        migrations.DeleteModel(
            name='Anklet',
        ),
        migrations.DeleteModel(
            name='Noise',
        ),
        migrations.AddField(
            model_name='location',
            name='idstaticnode',
            field=models.ForeignKey(blank=True, db_column='idStaticNode', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Staticnode'),
        ),
        migrations.AddField(
            model_name='cowculatedlocation',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral'),
        ),
        migrations.AddField(
            model_name='cowculatedlocation',
            name='idrssiused',
            field=models.ForeignKey(blank=True, db_column='idRssiUsed', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Location'),
        ),
        migrations.AddField(
            model_name='ankletgeneral',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral'),
        ),
        migrations.AddField(
            model_name='ankletgeneral',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral'),
        ),
        migrations.AddField(
            model_name='accelerometer',
            name='idanklet',
            field=models.ForeignKey(blank=True, db_column='idAnklet', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AnkletGeneral'),
        ),
        migrations.AddField(
            model_name='accelerometer',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='idanklet',
            field=models.ForeignKey(blank=True, db_column='idAnklet', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AnkletGeneral'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral'),
        ),
    ]
