# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160402_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankletgeneral',
            name='iduser',
            field=models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staticnode',
            name='iduser',
            field=models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperaturelevel',
            field=models.DecimalField(blank=True, db_column='temperatureLevel', decimal_places=2, max_digits=5, null=True),
        ),
    ]
