# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20160403_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankletgeneral',
            name='idcow',
        ),
        migrations.AddField(
            model_name='cowgeneral',
            name='idanklet',
            field=models.ForeignKey(blank=True, db_column='idAnklet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cow', to='website.AnkletGeneral'),
        ),
        migrations.AlterField(
            model_name='ankletgeneral',
            name='iduser',
            field=models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='idtemperature',
            field=models.IntegerField(db_column='idTemperature', primary_key=True, serialize=False),
        ),
    ]
