# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20160405_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowgeneral',
            name='idanklet',
        ),
        migrations.AddField(
            model_name='ankletgeneral',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cowid', to='website.CowGeneral'),
        ),
    ]
