# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0018_auto_20160406_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowgeneral',
            name='iduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cow_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
