# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_cowgeneral_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankletgeneral',
            name='idanklet',
            field=models.IntegerField(db_column='idAnklet', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ankletgeneral',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cow_anklet', to='website.CowGeneral'),
        ),
        migrations.AlterField(
            model_name='cowgeneral',
            name='idcow',
            field=models.IntegerField(db_column='idCow', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cowgeneral',
            name='iduser',
            field=models.ForeignKey(db_column='iduser_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cow_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cow_temperature', to='website.CowGeneral'),
        ),
    ]
