# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20160406_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankletgeneral',
            name='idanklet',
            field=models.AutoField(db_column='idAnklet', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cowgeneral',
            name='idcow',
            field=models.AutoField(db_column='idCow', primary_key=True, serialize=False),
        ),
    ]
