# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20160406_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankletgeneral',
            name='iduser',
        ),
    ]
