# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20160408_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowgroups',
            name='cowgroupnum',
            field=models.IntegerField(null=True),
        ),
    ]
