# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_cowgroups_cowgroupnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevel',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cow_activity', to='website.CowGeneral'),
        ),
        migrations.AlterField(
            model_name='cowculatedlocation',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cow_location', to='website.CowGeneral'),
        ),
        migrations.AlterField(
            model_name='cowculatedlocation',
            name='idrssiused',
            field=models.ForeignKey(blank=True, db_column='idRssiUsed', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cow_rssi', to='website.Location'),
        ),
        migrations.AlterField(
            model_name='cowgroups',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cow_group', to='website.CowGeneral'),
        ),
        migrations.AlterField(
            model_name='microphone',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cow_noise', to='website.CowGeneral'),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cow_pulse', to='website.CowGeneral'),
        ),
        migrations.AlterField(
            model_name='sociallevel',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cow_social', to='website.CowGeneral'),
        ),
        migrations.AlterField(
            model_name='stepcount',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cow_stepcount', to='website.CowGeneral'),
        ),
    ]
