# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_activitylevel_sleepingpercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microphoneaverage',
            fields=[
                ('idmicrophoneaverage', models.AutoField(db_column='idMicrophoneAverage', primary_key=True, serialize=False)),
                ('micaverage', models.FloatField(blank=True, db_column='micAverage', null=True)),
                ('timemeasured', models.DateTimeField(blank=True, db_column='timeMeasured', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'microphoneAverage',
            },
        ),
        migrations.AlterField(
            model_name='microphone',
            name='idcow',
            field=models.ForeignKey(blank=True, db_column='idCow', default=6, on_delete=django.db.models.deletion.CASCADE, to='website.CowGeneral'),
        ),
    ]
