# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20160417_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stepcountaverages',
            fields=[
                ('idstepcountaverages', models.AutoField(db_column='idstepCountAverages', primary_key=True, serialize=False)),
                ('idcow', models.IntegerField(db_column='idCow')),
                ('datastarttime', models.TimeField(blank=True, db_column='dataStartTime', null=True)),
                ('dataendtime', models.TimeField(blank=True, db_column='dataEndTime', null=True)),
                ('stepcountavg', models.FloatField(blank=True, db_column='stepCountAvg', null=True)),
                ('numaverages', models.IntegerField(blank=True, db_column='numAverages', null=True)),
                ('lastupdated', models.DateTimeField(blank=True, db_column='lastUpdated', null=True)),
            ],
            options={
                'db_table': 'stepCountAverages',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='accelerometer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='activitylevel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ankletgeneral',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cowculatedlocation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cowgeneral',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cowgroups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='friendships',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='microphone',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pulse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sociallevel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='staticnode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stepcount',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'managed': False},
        ),
    ]
