######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 24 19:01:53 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/y/i/yida/Desktop/qt/. .

# Input
HEADERS += qt.h
SOURCES += main.cpp qt.cpp
